# -*- coding: utf-8 -*-
"""img classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EbV2YgflhotT-JT80lPWao8gR8FFJvD2
"""

import numpy as np
import random
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

"""### Load Dataset"""

from google.colab import drive
drive.mount('/content/drive')

X_train= np.loadtxt('/content/drive/My Drive/img classification/folder/input.csv', delimiter=',')
Y_train= np.loadtxt('/content/drive/My Drive/img classification/folder/labels.csv', delimiter=',')

X_test= np.loadtxt('/content/drive/My Drive/img classification/folder/input_test.csv',delimiter=',')
Y_test= np.loadtxt('/content/drive/My Drive/img classification/folder/labels_test.csv', delimiter=',')

X_train= X_train.reshape(len(X_train),100,100,3)
Y_train= Y_train.reshape(len(Y_train),1)
X_test = X_test.reshape(len(X_test),100,100,3)
Y_test= Y_test.reshape(len(Y_test),1)

X_train= X_train/255
X_test= X_test/255

print("Shape of X_train: ", X_train.shape)
print("Shape of Y_train: ", Y_train.shape)
print("Shape of X_test: ", X_test.shape)
print("Shape of Y_test: ", Y_test.shape)

X_train[1,:]

idx= random.randint(0, len(X_train))
plt.imshow(X_train[idx, :])
plt.show()

"""## Model"""

model= Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape= (100, 100, 3)),
    MaxPooling2D((2,2)),

    Flatten(),
    Dense(64, activation= 'relu'),
    Dense(1, activation='sigmoid'),
])

model.compile(loss= 'binary_crossentropy',optimizer='adam', metrics=['accuracy'])

"""## Training the input data"""

model.fit(X_train, Y_train, epochs= 5, batch_size=64)

model.evaluate(X_test,Y_test)

"""## Making Predictions"""

idx2= random.randint(0, len(Y_test))
plt.imshow(X_test[idx2, :])
plt.show()

Y_pred= model.predict(X_test[idx2,:].reshape(1, 100, 100,3))
print(Y_pred) 

Y_pred= Y_pred > 0.5
if(Y_pred==0):
  pred='dog'
else:
  pred='cat'  

print("our model says it is a :",pred)